### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ITesserakt** [ITesserakt/diskordin#1]
- [x] Create README
- [x] Post this framework into a repository and make it available for Gradle, Maven
- [x] Cache data from gateway events *(Almost done)*
- [x] Split project to independent modules to lower coupling
- [ ] Make rate limiter
- [x] Make sharding mechanic
- [x] Use `Intents` (https://github.com/discordapp/discord-api-docs/pull/1307)
- [ ] Wait while [Arrow Meta](https://github.com/arrow-kt/arrow-meta) come to release and use it
- [x] Make command module
- [ ] Write tests
- [ ] Write __a lot__ of documentation
- [x] Rewrite from Arrow's `Fx` to [`Fx-Coroutines`](https://github.com/arrow-kt/arrow-fx/blob/master/arrow-fx-coroutines/README.MD)
 - [ ] Remove kinds as it will be deleted in Arrow 0.13.0
 - [ ] Rewrite shard controller with more readable construction using actors
 - [ ] Replace most of the typeclasses with `fun interfaces`

**Comment by ITesserakt** [comment]
### Some additions
- [ ] Write tests
- [ ] Wait while [Arrow Meta](https://github.com/arrow-kt/arrow-meta) come to alpha and use it

**Comment by ITesserakt** [comment]
**It seems that rate limitter have already implemented because I didn\`t face with `429` http code. Though I performed a lot of operations quite quickly.**
